name: Deploy Production

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: "npm"
      - name: Create .env file
        run: echo "${{secrets.ENV_PRODUCTION}}" > .env
      - name: Build docker image
        run: docker build --platform linux/amd64 -t daisynguyennnnn/nextjs:v0 .
      - name: Login Docker hub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Push docker image
        run: docker push daisynguyennnnn/nextjs:v0
      - run: npm i --force
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            sudo docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
            sudo docker pull daisynguyennnnn/nestjs:v0
            sudo docker stop dockernext
            sudo docker rm dockernext
            sudo docker run -d -p 3000:3000 --name dockernext daisynguyennnnn/nextjs:v0
            sudo docker image prune -f
